local ffi = require("ffi")

if not __HTTPREQUESTID_H__ then
__HTTPREQUESTID_H__ = true
require ("win32.winapifamily")


if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP , WINAPI_PARTITION_SYSTEM) then

ffi.cdef[[
static const int DISPID_HTTPREQUEST_BASE                   =  0x00000001;


static const int DISPID_HTTPREQUEST_OPEN                    = (DISPID_HTTPREQUEST_BASE);
static const int DISPID_HTTPREQUEST_SETREQUESTHEADER        = (DISPID_HTTPREQUEST_BASE + 1);
static const int DISPID_HTTPREQUEST_GETRESPONSEHEADER       = (DISPID_HTTPREQUEST_BASE + 2);
static const int DISPID_HTTPREQUEST_GETALLRESPONSEHEADERS   = (DISPID_HTTPREQUEST_BASE + 3);
static const int DISPID_HTTPREQUEST_SEND                    = (DISPID_HTTPREQUEST_BASE + 4);
static const int DISPID_HTTPREQUEST_OPTION                  = (DISPID_HTTPREQUEST_BASE + 5);
static const int DISPID_HTTPREQUEST_STATUS                  = (DISPID_HTTPREQUEST_BASE + 6);
static const int DISPID_HTTPREQUEST_STATUSTEXT              = (DISPID_HTTPREQUEST_BASE + 7);
static const int DISPID_HTTPREQUEST_RESPONSETEXT            = (DISPID_HTTPREQUEST_BASE + 8);
static const int DISPID_HTTPREQUEST_RESPONSEBODY            = (DISPID_HTTPREQUEST_BASE + 9);
static const int DISPID_HTTPREQUEST_RESPONSESTREAM          = (DISPID_HTTPREQUEST_BASE + 10);
static const int DISPID_HTTPREQUEST_ABORT                   = (DISPID_HTTPREQUEST_BASE + 11);
static const int DISPID_HTTPREQUEST_SETPROXY                = (DISPID_HTTPREQUEST_BASE + 12);
static const int DISPID_HTTPREQUEST_SETCREDENTIALS          = (DISPID_HTTPREQUEST_BASE + 13);
static const int DISPID_HTTPREQUEST_WAITFORRESPONSE         = (DISPID_HTTPREQUEST_BASE + 14);
static const int DISPID_HTTPREQUEST_SETTIMEOUTS             = (DISPID_HTTPREQUEST_BASE + 15);
static const int DISPID_HTTPREQUEST_SETCLIENTCERTIFICATE    = (DISPID_HTTPREQUEST_BASE + 16);
static const int DISPID_HTTPREQUEST_SETAUTOLOGONPOLICY      = (DISPID_HTTPREQUEST_BASE + 17);
]]

end --/* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */


end --// __HTTPREQUESTID_H__
